// workers/api/scripts/seed-articles.ts
//
// Seed script for the 100-article content batch. Run with:
//
//   npx tsx workers/api/scripts/seed-articles.ts
//
// What it does:
//   1. Imports all article data from `../content/articles`
//   2. Runs the 10 quality checks via `@brainverse/content-engine/quality-checker`
//   3. If all pass, generates D1 INSERT statements for the `articles`,
//      `article_translations`, and `seo_metadata` tables
//   4. Writes the SQL to `workers/api/scripts/seed-articles.sql`
//
// The generated SQL can be applied to D1 with:
//
//   wrangler d1 execute brainverse-db --file=workers/api/scripts/seed-articles.sql --local
//   wrangler d1 execute brainverse-db --file=workers/api/scripts/seed-articles.sql --remote

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { allArticles } from '../content/articles';
import type { ArticleData } from '../content/types';
import {
  checkBatchQuality,
  generateQualityReport,
} from '@brainverse/content-engine';

// ============ Main ============

async function main(): Promise<void> {
  console.log(`Loaded ${allArticles.length} article(s) from content/articles/\n`);

  // 1. Run quality checks
  const results = checkBatchQuality(allArticles, allArticles);
  const report = generateQualityReport(results);
  console.log(report);
  console.log('');

  const failed = results.filter((r) => !r.passed);
  if (failed.length > 0) {
    console.error(`${failed.length} article(s) failed quality checks!`);
    console.error('Fix the errors above before generating seed SQL.');
    process.exit(1);
  }

  // 2. Generate SQL
  const sql = generateSeedSql(allArticles);

  // 3. Write to file
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const outputPath = resolve(__dirname, 'seed-articles.sql');
  writeFileSync(outputPath, sql, 'utf-8');

  console.log(`\nSeed SQL written to: ${outputPath}`);
  console.log(`Total INSERT statements: ${countInserts(sql)}`);
  console.log('\nApply to D1 with:');
  console.log(
    '  wrangler d1 execute brainverse-db --file=workers/api/scripts/seed-articles.sql --local',
  );
}

// ============ SQL generation ============

/** Fixed timestamp for deterministic seeding (idempotent re-runs). */
const SEED_TIMESTAMP = '2026-06-25T00:00:00.000Z';

/** Locales that get a translation + SEO metadata row per article. */
const LOCALES: readonly ('en' | 'zh' | 'ja')[] = ['en', 'zh', 'ja'] as const;

/**
 * Generate the full seed SQL for all articles.
 *
 * Produces `INSERT OR REPLACE` statements (idempotent) for:
 *   - `articles` (1 row per article)
 *   - `article_translations` (3 rows per article — en / zh / ja)
 *   - `seo_metadata` (3 rows per article — en / zh / ja)
 */
function generateSeedSql(articles: ArticleData[]): string {
  const lines: string[] = [
    '-- seed-articles.sql',
    '-- Auto-generated by workers/api/scripts/seed-articles.ts',
    `-- Generated: ${new Date().toISOString()}`,
    `-- Articles: ${articles.length}`,
    '',
    '-- Idempotent: uses INSERT OR REPLACE so re-running is safe.',
    '',
    'BEGIN TRANSACTION;',
    '',
  ];

  for (const article of articles) {
    lines.push(...generateArticleSql(article));
    lines.push('');
  }

  lines.push('COMMIT;');

  return lines.join('\n');
}

/** Generate INSERT statements for a single article and its translations/SEO. */
function generateArticleSql(article: ArticleData): string[] {
  const articleId = `art-${article.slug}`;
  const lines: string[] = [];

  // --- articles row ---
  lines.push('-- ' + article.slug);
  lines.push(
    `INSERT OR REPLACE INTO articles (id, slug, category, published, featured, sort_order, created_at, updated_at)`,
  );
  lines.push(
    `VALUES (${sqlString(articleId)}, ${sqlString(article.slug)}, ${sqlString(article.category)}, 1, ${article.featured ? 1 : 0}, ${article.sortOrder}, ${sqlString(SEED_TIMESTAMP)}, ${sqlString(SEED_TIMESTAMP)});`,
  );

  // --- article_translations + seo_metadata rows (one per locale) ---
  for (const locale of LOCALES) {
    const translation = article.translations[locale];
    const seo = article.seoMetadata[locale];
    const translationId = `art-${article.slug}-${locale}`;
    const seoId = `seo-${article.slug}-${locale}`;

    lines.push('');
    lines.push(`-- ${article.slug} / ${locale}`);

    // article_translations
    lines.push(
      `INSERT OR REPLACE INTO article_translations (id, article_id, locale, title, meta_description, content, faq, created_at, updated_at)`,
    );
    lines.push(
      `VALUES (${sqlString(translationId)}, ${sqlString(articleId)}, ${sqlString(locale)}, ${sqlString(translation.title)}, ${sqlString(translation.metaDescription)}, ${sqlString(translation.content)}, ${sqlString(JSON.stringify(translation.faq))}, ${sqlString(SEED_TIMESTAMP)}, ${sqlString(SEED_TIMESTAMP)});`,
    );

    // seo_metadata
    lines.push(
      `INSERT OR REPLACE INTO seo_metadata (id, entity_type, entity_id, locale, title, description, canonical_url, json_ld, created_at)`,
    );
    lines.push(
      `VALUES (${sqlString(seoId)}, 'article', ${sqlString(articleId)}, ${sqlString(locale)}, ${sqlString(seo.title)}, ${sqlString(seo.description)}, ${sqlString(seo.canonicalUrl)}, ${sqlString(seo.jsonLd)}, ${sqlString(SEED_TIMESTAMP)});`,
    );
  }

  return lines;
}

// ============ SQL helpers ============

/**
 * Escape a string for safe inclusion in a SQL single-quoted literal.
 * Doubles internal single quotes (`'` → `''`) and wraps the result in
 * single quotes.
 */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** Count the number of INSERT statements in the generated SQL. */
function countInserts(sql: string): number {
  const matches = sql.match(/INSERT\s+OR\s+REPLACE/gi);
  return matches ? matches.length : 0;
}

// ============ Run ============

main().catch((err) => {
  console.error('Seed script failed:', err);
  process.exit(1);
});
